import arviz as az
import numpy as np
from scipy.special import expit as invlogit

print("Loading posterior distributions...")
trace = az.from_netcdf(r"/content/drive/MyDrive/RL_for_IGT_HBA/Decision-model/Results/dual_system_hba_posterior.nc") # replace with the corrrect path of the posterior distrution file generated by hba.py

beta_flat = trace.posterior["mu_beta_raw"].values.reshape(-1, 3)
lambda_flat = trace.posterior["mu_lambda_raw"].values.reshape(-1, 3)
alpha_flat = trace.posterior["mu_alpha_raw"].values.reshape(-1, 3)
decay_flat = trace.posterior["mu_decay_raw"].values.reshape(-1, 3)

beta_pfc = invlogit(beta_flat)
loss_aversion = np.exp(lambda_flat)
alpha_limbic = invlogit(alpha_flat)
memory_decay = invlogit(decay_flat)

def print_significance(param_name, data):
    mean_ctrl = np.mean(data[:, 0])
    mean_hero = np.mean(data[:, 1])
    mean_amph = np.mean(data[:, 2])
    
    print(f"\n--- {param_name} ---")
    print(f"Means: Control={mean_ctrl:.3f}, Heroin={mean_hero:.3f}, Amphetamine={mean_amph:.3f}")
    
    p_c_gt_h = np.mean(data[:, 0] > data[:, 1])
    p_c_gt_a = np.mean(data[:, 0] > data[:, 2])
    p_a_gt_h = np.mean(data[:, 2] > data[:, 1])
    
    print(f"P(Control > Heroin)      = {p_c_gt_h:.4f}")
    print(f"P(Control > Amphetamine) = {p_c_gt_a:.4f}")
    print(f"P(Amphetamine > Heroin)  = {p_a_gt_h:.4f}")

print("\n=== BAYESIAN SIGNIFICANCE RESULTS ===")
print_significance("1. PFC Dominance (Beta)", beta_pfc)
print_significance("2. Loss Aversion (Lambda)", loss_aversion)
print_significance("3. Limbic Learning Rate (Alpha)", alpha_limbic)
print_significance("4. Memory Decay (d)", memory_decay)